version: '3.0'
services:
  main:
    image: harbor.oshteam.ru/excel_screenshots/backend
    container_name: main
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: npm run start
    restart: always